export const traductions = {
  fr: {
    nom: 'Français',
    drapeau: '🇫🇷',
    direction: 'ltr',
    accueil: 'Accueil',
    produits: 'Produits',
    agriculteurs: 'Agriculteurs',
    admin: '🔐 Admin',
    connexion: '🔐 Connexion',
    deconnexion: 'Déconnexion',
    slogan: 'Connecter les producteurs, développer l\'agriculture, nourrir l\'avenir.',
    titre_hero: '🌾 La plateforme agricole numérique de Guinée',
    inscrire_agriculteur: 'S\'inscrire comme agriculteur',
    voir_produits: 'Voir les produits',
    comment_ca_marche: 'Comment ça marche ?',
    simple_gratuit: 'Simple, rapide et gratuit pour les agriculteurs',
    nos_produits: 'Nos produits agricoles',
    acheter_direct: 'Achetez directement auprès des producteurs guinéens',
    rejoignez: '🌿 Rejoignez Guinea Agri Market aujourd\'hui !',
    attendent: 'Plus de 10 000 agriculteurs vous attendent sur la plateforme',
    inscrire_gratuit: 'S\'inscrire gratuitement',
    etape1_titre: 'Créez votre profil',
    etape1_desc: 'Inscrivez-vous gratuitement et publiez vos récoltes disponibles avec photos et prix.',
    etape2_titre: 'Connectez-vous',
    etape2_desc: 'Les acheteurs vous trouvent et vous contactent directement via WhatsApp ou téléphone.',
    etape3_titre: 'Vendez au meilleur prix',
    etape3_desc: 'Négociez directement sans intermédiaire et recevez votre paiement en toute sécurité.',
    agriculteurs_stat: 'Agriculteurs',
    regions_stat: 'Régions couvertes',
    produits_stat: 'Produits agricoles',
    acheteurs_stat: 'Acheteurs actifs',
  },

  ar: {
    nom: 'العربية',
    drapeau: '🇸🇦',
    direction: 'rtl',
    accueil: 'الرئيسية',
    produits: 'المنتجات',
    agriculteurs: 'المزارعون',
    admin: '🔐 الإدارة',
    connexion: '🔐 تسجيل الدخول',
    deconnexion: 'تسجيل الخروج',
    slogan: 'ربط المنتجين، تطوير الزراعة، إطعام المستقبل.',
    titre_hero: '🌾 المنصة الزراعية الرقمية لغينيا',
    inscrire_agriculteur: 'التسجيل كمزارع',
    voir_produits: 'عرض المنتجات',
    comment_ca_marche: 'كيف يعمل؟',
    simple_gratuit: 'بسيط وسريع ومجاني للمزارعين',
    nos_produits: 'منتجاتنا الزراعية',
    acheter_direct: 'اشتر مباشرة من المنتجين الغينيين',
    rejoignez: '🌿 انضم إلى Guinea Agri Market اليوم!',
    attendent: 'أكثر من 10,000 مزارع ينتظرونك على المنصة',
    inscrire_gratuit: 'التسجيل مجاناً',
    etape1_titre: 'أنشئ ملفك الشخصي',
    etape1_desc: 'سجل مجاناً وانشر محاصيلك المتاحة مع الصور والأسعار.',
    etape2_titre: 'تواصل',
    etape2_desc: 'يجدك المشترون ويتواصلون معك مباشرة عبر واتساب أو الهاتف.',
    etape3_titre: 'بع بأفضل سعر',
    etape3_desc: 'تفاوض مباشرة بدون وسيط واستلم دفعتك بأمان.',
    agriculteurs_stat: 'مزارع',
    regions_stat: 'منطقة مغطاة',
    produits_stat: 'منتج زراعي',
    acheteurs_stat: 'مشترٍ نشط',
  },

  pular: {
    nom: 'Pular',
    drapeau: '🇬🇳',
    direction: 'ltr',
    accueil: 'Galle',
    produits: 'Liggey',
    agriculteurs: 'Njuɓɓorɓe',
    admin: '🔐 Janngo',
    connexion: '🔐 Naatde',
    deconnexion: 'Yaltude',
    slogan: 'Laaɓnude njuɓɓorɓe, renndinde ngesa, ƴeewde nyawde.',
    titre_hero: '🌾 Laawol binndol ngesa Gine',
    inscrire_agriculteur: 'Winndude njuɓɓoowo',
    voir_produits: 'Yiy\'de liggey',
    comment_ca_marche: 'No waɗata?',
    simple_gratuit: 'Yoɓaani, ɓuri yaawde njuɓɓorɓe',
    nos_produits: 'Liggey amen ngesa',
    acheter_direct: 'So\'o tigi njuɓɓorɓe Gine',
    rejoignez: '🌿 Naatu Guinea Agri Market hannde!',
    attendent: 'Ɗo njuɓɓorɓe 10 000 nganndi ma',
    inscrire_gratuit: 'Winndude yoɓaani',
    etape1_titre: 'Winnd doosiyel maa',
    etape1_desc: 'Winndude yoɓaani kadi jaɓɓino liggey maa kala.',
    etape2_titre: 'Naatnu',
    etape2_desc: 'So\'ooɓe nganndi ma kadi mbaɗa WhatsApp.',
    etape3_titre: 'Yoɓ nafam',
    etape3_desc: 'Sago tigi yoɓde kadi heɓ ceede maa.',
    agriculteurs_stat: 'Njuɓɓorɓe',
    regions_stat: 'Diwe naataaɗe',
    produits_stat: 'Liggey ngesa',
    acheteurs_stat: 'So\'ooɓe',
  },

  soussou: {
    nom: 'Soussou',
    drapeau: '🇬🇳',
    direction: 'ltr',
    accueil: 'Banxi',
    produits: 'Soso',
    agriculteurs: 'Forɛɛ gbilimɛ',
    admin: '🔐 Manageur',
    connexion: '🔐 Sɛnbɛ',
    deconnexion: 'Bɔ',
    slogan: 'Forɛɛ gbilimɛ rabamɛ, forɛɛ gbamu, wanla xɔnɔ.',
    titre_hero: '🌾 Guinea forɛɛ platform numerique',
    inscrire_agriculteur: 'Forɛɛ gbilimɛ sɛnbɛ',
    voir_produits: 'Soso toma',
    comment_ca_marche: 'Mundu wa nɔ?',
    simple_gratuit: 'Nɔ malɛ, nɔ forɛɛ gbilimɛ',
    nos_produits: 'Forɛɛ soso',
    acheter_direct: 'Guinea forɛɛ gbilimɛ xili soso',
    rejoignez: '🌿 Guinea Agri Market sɛnbɛ!',
    attendent: 'Forɛɛ gbilimɛ 10 000 i ma xa',
    inscrire_gratuit: 'Sɛnbɛ nɔ malɛ',
    etape1_titre: 'I sɛnbɛ xa',
    etape1_desc: 'Sɛnbɛ nɔ malɛ kadi i soso xa mɛ.',
    etape2_titre: 'Rabamɛ',
    etape2_desc: 'Xilimɛ i ma kadi WhatsApp.',
    etape3_titre: 'Soso nafam',
    etape3_desc: 'Tigi xili kadi i wari xa.',
    agriculteurs_stat: 'Forɛɛ gbilimɛ',
    regions_stat: 'Diw',
    produits_stat: 'Soso',
    acheteurs_stat: 'Xilimɛ',
  },

  maninka: {
    nom: 'Maninka',
    drapeau: '🇬🇳',
    direction: 'ltr',
    accueil: 'So',
    produits: 'Fɛnw',
    agriculteurs: 'Sansɛbaliw',
    admin: '🔐 Faamalaw',
    connexion: '🔐 Dɔn',
    deconnexion: 'Bɔ',
    slogan: 'Sansɛbaliw lajɛ, sansɛbali kɛ, sɔn.',
    titre_hero: '🌾 Guinea sansɛbali platform numerique',
    inscrire_agriculteur: 'Sansɛbali sɛbɛ',
    voir_produits: 'Fɛnw ye',
    comment_ca_marche: 'Mun kɛra?',
    simple_gratuit: 'Nɔgɔya, teliya ani nɔgɔn sansɛbaliw ye',
    nos_produits: 'An ka sansɛbali fɛnw',
    acheter_direct: 'Guinea sansɛbaliw fɛ fɛnw san',
    rejoignez: '🌿 Guinea Agri Market dɔn sisan!',
    attendent: 'Sansɛbali 10 000 b\'i makɔnɔ',
    inscrire_gratuit: 'Sɛbɛ nɔgɔn na',
    etape1_titre: 'I ka dosiye sɛbɛ',
    etape1_desc: 'Sɛbɛ nɔgɔn na ani i ka fɛnw jira.',
    etape2_titre: 'Lajɛ',
    etape2_desc: 'Sariliw b\'i sɔrɔ ani WhatsApp.',
    etape3_titre: 'Jaabi ɲuman na',
    etape3_desc: 'Tigi lajɛ ani i ka wari sɔrɔ.',
    agriculteurs_stat: 'Sansɛbaliw',
    regions_stat: 'Mara',
    produits_stat: 'Fɛnw',
    acheteurs_stat: 'Sariliw',
  },
}